site_name: Learning FROST from the Command Line
site_url: https://learningfrost.blockchaincommons.com
repo_url: https://github.com/BlockchainCommons/Learning-FROST-from-the-Command-Line

theme:
  name: material
  color_mode: dark
  user_color_mode_toggle: true
  icon:
    logo: material/snowflake
